### ISSUE TITLE
Show example code comparing HEV rdt positives v negatives

### ISSUE THREAD

**Issue by zkamvar** [R4EPI/R4EPIs-website#19]
@nsbatra - dont know how much time you have. But if you do, and the other stuff is cleared. 
Could you show some example code comparing HEV rdt postives versus negatives. Either in the walkthrough or in a seperate tab called statistical testing?
Run tab_univariate to produce odds ratios. And maybe example codes comparing groups with chi-squared tests, and potentially also t-tests (though preferably kruskal-wallis tests). Have example code if you need!

_Originally posted by @aspina7 in https://github.com/R4EPI/R4EPIs-website/pull/17/files_

**Comment by nsbatra** [comment]
Noted. Yes, I can put this together this week.
