### ISSUE TITLE
Link to ggplot2 extension gallery needs updating

### ISSUE THREAD

**Issue by aspina7** [R4EPI/R4EPIs-website#56]
Under [advanced and miscellaneous](https://r4epis.netlify.app/training/r_basics/advanced_functions/), need to change the link to ggplot graph gallery, currently sends to some non-savoury material 
needs to be changed to: 
https://r4epis.netlify.app/training/r_basics/advanced_functions/

**Comment by pbkeating** [comment]
Updated link
